version: '2.2'

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: ./docker/docker.django
    restart: always
    command: [ "./django_entrypoint.sh" ]
    env_file:
      - ./.env
    depends_on:
      - database
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  react:
    container_name: react
    build:
      context: .
      dockerfile: ./docker/docker.react
    ports:
      - "3000:3000"
    depends_on:
      - django
    volumes:
      - ./frontend:/frontend
      - ./frontend/node_modules
      - ./frontend/.next
    restart: always

  database:
    image: postgres:13-alpine
    container_name: database
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./db/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - 5432

volumes:
  static-files: null
  db-data: null
